logging:
  level:
    io.eventuate: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventuate
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eventuatelocal:
  kafka:
    bootstrap:
      servers: 172.27.128.38:9092,172.27.128.39:9092
  zookeeper:
    connection:
      string: 172.27.128.38:2181,172.27.128.39:2181
server:
  port: 8085

eventuate:
  database:
    schema: eventuate